# this is an practise example with EC2 API
# The Swagger specification link http://swagger.io/specification/ and the DOM of Swagger http://openapi-specification-visual-documentation.apihandyman.io/
swagger: '2.0'
info:
  version: 1.0.0
  title: Swagger SharedEV
  description: "This is the API of shared EV service."
  license:
    name: Example 2.0
    url: http://www.example.com/licenses/LICENSE-2.0.html

host: "example.com"
basePath: "/"
schemes:
  - "http"
  - "https"

consumes:
  - application/json
produces:
  - application/json

tags:
  - name: Trip
    description: "API about trip of driver"
  - name: Requirement
    description: "API about request from passager"

responses:
  BadRequest400:
    description: Bad Request
    schema:
      $ref: '#/definitions/failure'
  Unauthorized401:
    description: Unauthorized
  ServerError500:
    description: Unexpected error
    headers:
      Content-Type:
        type: string
        description: the response media type
    schema:
      $ref: '#/definitions/failure'
paths:
  /trips:
    post:
      summary: 司机发布行程
      operationId: pubTrips
      tags:
        - Trip
      parameters:
        - name: origination
          in: query
          description: 出发地址
          type: string
          required: false
        - name: destination
          in: query
          description: 到达地址
          type: string
          required: false
      responses:
        201:
          description: OK
          schema:
            $ref: '#/definitions/TripResponse'
        401:
          description: Unauthorized
          headers:
            Content-Type:
              type: string
              description: the response media type
        406:
          description: Not Acceptable
          headers:
            Content-Type:
              type: string
              description: the response media type
        500:
          description: Unexpected error
          headers:
            Content-Type:
              type: string
              description: the response media type
          schema:
            $ref: '#/definitions/failure'
  /requirements:
      post:
        summary: 乘客发布需求
        operationId: sendRequirements
        tags:
          - Requirement
        parameters:
          - name: origination
            in: query
            description: 出发地址
            type: string
            required: false
          - name: destination
            in: query
            description: 到达地址
            type: string
            required: false
        responses:
          201:
            description: OK
            schema:
              $ref: '#/definitions/RequirementsResponse'
          401:
            description: Unauthorized
            headers:
              Content-Type:
                type: string
                description: the response media type
          406:
            description: Not Acceptable
            headers:
              Content-Type:
                type: string
                description: the response media type
          500:
            description: Unexpected error
            headers:
              Content-Type:
                type: string
                description: the response media type
            schema:
              $ref: '#/definitions/failure'
definitions:
  TripResponse:
    type: object
    properties:
      origination:
        type: string
      destination:
        type: string
  RequirementsResponse:
    type: object
    properties:
      origination:
        type: string
      destination:
        type: string
  failure:
    type: object
    properties:
      errors:
        type: array
        items:
          $ref: '#/definitions/error'
      meta:
        $ref: '#/definitions/meta'
  error:
    type: object
    properties:
      id:
        description: A unique identifier for the occurrence of the problem
        type: string
      links:
        $ref: '#/definitions/links'
      status:
        description: Http status code
        type: string
      code:
        description: Application specific error code
        type: string
      title:
        type: string
      detail:
        type: string
      source:
        type: object
        properties:
          pointer:
            description: A JSON Pointer[RFC6901] to associated entity in the request document. [e.g. /data for data object, /data/attributes/title for specific attribute
            type: string
          parameter:
            description: A string indicating which query parameter caused error
            type: string
      meta:
        $ref: '#/definitions/meta'
  meta:
    type: object
  links:
    type: array
    items:
      type: object
      properties:
        href:
          type: string
        rel:
          type: string